---
title: "Shiny Data Cleaning"
output: pdf_document
classoption: landscape
---

```{r setup, include=FALSE, echo = FALSE}
library(tidyverse)
library(pander)
library(knitr)
library(plyr)
library(gridExtra) 
library(readr)
knitr::opts_chunk$set(warning = FALSE, message = FALSE) 
#knitr::opts_chunk$set(echo=F, 
#                      eval=T,
#                      cache=F,
#                      results='markup', 
#                      message=F,
#                      warning=F, 
#                      fig.height=3,
#                      fig.width=4,
#                      fig.align='center')
```

```{r, include = FALSE}
# enter csv name
total <- read.csv(file = "allGames.csv")
# removing BS tags, pitchouts etc
total <- total %>% subset(TaggedPitchType != "Other")
total <- total %>% subset(TaggedPitchType != "Knuckleball")
# just ucla guys, not really necessary line
total <- total %>% subset(PitcherTeam == "UCLA")
# remove first names and commas
total$Pitcher <- gsub("(.*),.*", "\\1", total$Pitcher)
# order pitches so you dont have to later
total$TaggedPitchType <- factor(total$TaggedPitchType, levels = c("Fastball", "Sinker","Cutter", "Curveball", "Slider", "Sweeper", "ChangeUp", "Splitter"))
# total$AbbPitchType
total$Date <- as.Date(total$Date, "%m/%d/%Y")
```

```{r, include = FALSE}
scrimData <- total %>% group_by("Pitcher") %>% group_by("TaggedPitchType")
# Overall
# Function to convert a time in HH:MM:SS format to a numeric value representing the number of seconds
convert_to_seconds <- function(hand, time) {
  time_parts <- strsplit(time, ":")[[1]]
  hours <- as.numeric(time_parts[1])
  minutes <- as.numeric(time_parts[2])
  seconds <- as.numeric(time_parts[3])
  # If the hours equals 12 and is a righty, assume it is on the next day
  # without this, average of 12:30 and 1:00 spits junk value around 6:00,
  # instead of 12:45
  hours <- ifelse(hand == "Right" & hours == 12, 0, hours)
  return(hours * 3600 + minutes * 60 + seconds)
}

# Function to convert a numeric value representing the number of seconds to a time in HH:MM:SS format
convert_to_time <- function(seconds) {
  hours <- as.integer(floor(seconds / 3600))
  minutes <- as.integer(floor(seconds %% 3600 / 60))
  seconds <- as.integer(seconds %% 60)
  # If the time is 12:00:00 or later, assume it is on the next day
  hours <- ifelse(hours == 0, 12, hours)
  
  return(sprintf("%d:%02d", hours, minutes))
}

# manipulate tilt 
tiltData <- scrimData %>% select('Pitcher','TaggedPitchType', 'PitcherThrows','Tilt')
tiltData <- tiltData %>%
  filter(Tilt!='')
# add seconds on to use functions from above
tiltData$Tilt <- paste0(tiltData$Tilt, ":00")

# Convert the times to numeric values representing the number of seconds
tiltData$secTilt <- mapply(convert_to_seconds, tiltData$PitcherThrows, tiltData$Tilt)


# Calculate the average of the numeric values
tiltSummary <- aggregate(tiltData[, 6], list(Pitcher = tiltData$Pitcher, TaggedPitchType = tiltData$TaggedPitchType), mean, na.rm = TRUE)

# Convert the average back to a time in HH:MM:SS format
seconds <- tiltSummary$secTilt
tiltSummary$AveTilt <- convert_to_time(seconds)
tiltSummary = subset(tiltSummary, select = -secTilt )
```

```{r}
cleaned <- merge(total, tiltSummary, by = c("Pitcher", "TaggedPitchType"), all = TRUE)
#write.csv(cleaned, "C:\\Users\\tbeer\\Documents\\UCLA\\Baseball Analytics\\Shiny\\Postgame-Report\\cleanedGames.csv", row.names = FALSE)
```



```{r, include = FALSE}
# #overall
# # creates various columns to indicate (0 or 1) strikes, whiffs, etc
# strikeData <- scrimSum %>% select('Pitcher','TaggedPitchType','PitchCall')
# strikeData$PitchNum <- ifelse(strikeData$PitchCall == 'BallCalled', 1, 1)
# strikeData$StrNum <- ifelse(grepl("^Ball",strikeData$PitchCall), 0, 1)
# strikeData$SwingNum <- ifelse(strikeData$PitchCall == 'StrikeSwinging', 1, 
#                       ifelse(strikeData$PitchCall == 'FoulBall', 1, 
#                         ifelse(strikeData$PitchCall == 'InPlay', 1, 0)
#                         )
#                      )
# strikeData$WhiffNum <- ifelse(strikeData$PitchCall == 'StrikeSwinging', 1, 0)
# 
# # count totals for each category
# scrimStrikeSum <- aggregate(strikeData[,c(5:8)], list(Pitcher = strikeData$Pitcher, Pitch = strikeData$TaggedPitchType), sum, na.rm = TRUE)
# 
# # total pitches per guy
# tot <- aggregate(scrimStrikeSum[,3], list(Pitcher = scrimStrikeSum$Pitcher), sum, na.rm = TRUE)
# 
# # add total pitches to dataframe to create usages
# scrimStrikeSum <- scrimStrikeSum %>% 
#   left_join(tot, by = "Pitcher")
# scrimStrikeSum <- scrimStrikeSum %>% add_column(Usage = round(scrimStrikeSum$PitchNum/scrimStrikeSum$x*100, 2), .after = "Pitch")
# 
# # converts to percentages
# scrimStrikeSum$StrP <- (scrimStrikeSum$StrNum/scrimStrikeSum$PitchNum)*100
# scrimStrikeSum$SwStrP <- (scrimStrikeSum$WhiffNum/scrimStrikeSum$PitchNum)*100
# scrimStrikeSum$WhiffP <- (scrimStrikeSum$WhiffNum/scrimStrikeSum$SwingNum)*100
# 
# # remove unneeded counts
# scrimStrikeSum <- scrimStrikeSum[,c(1:4,9:11)]
```

```{r, include = FALSE}
# # ball in play data
# inplayData <- scrimData %>% select('Pitcher','TaggedPitchType','PitchCall','ExitSpeed', 'Angle')
# inplayData <- na.omit(inplayData)
# inplayData <- inplayData[inplayData$PitchCall == 'InPlay',]
# inplayData$BIP <- ifelse(inplayData$PitchCall == 'InPlay', 1, 0)
# 
# # average exit velocity and launch angle from balls put in play
# evSum <- aggregate(inplayData[,c(5:6)], list(Pitcher = inplayData$Pitcher, Pitch = inplayData$TaggedPitchType), mean, na.rm = TRUE)
# colnames(evSum)[3] <- "EV"
# colnames(evSum)[4] <- "LaunchAngle"
# 
# # number of balls put into play
# bip <- aggregate(inplayData[,7], list(Pitcher = inplayData$Pitcher, Pitch = inplayData$TaggedPitchType), sum, na.rm = TRUE)
# evSum$BIP <- bip$BIP
# 
# # merges strike/swing data with EV
# evSum <- merge(evSum, scrimStrikeSum, all = TRUE)
# 
# # round values
# evSum <- evSum %>% mutate_if(is.numeric, ~round(., 2))
# evSum <- evSum %>% mutate_at(c('Usage', 'StrP', 'SwStrP', 'WhiffP'), as.integer)
# 
# # paste percent sign for visuals
# evSum <- evSum %>% mutate_at(c('Usage', 'StrP', 'SwStrP', 'WhiffP'), as.character)
# evSum[,c(6,8:10)] <- lapply(evSum[,c(6,8:10)], paste0, '%')
```

